fueltanks = ["Land_Ind_TankSmall", "Land_fuel_tank_big", "Land_fuel_tank_stairs", "Land_fuel_tank_stairs_ep1", "Land_wagon_tanker", "Land_fuelstation", "Land_fuelstation_army", "Land_smd_fuelstation_army", "land_fuelstation_w", "Land_benzina_schnell"]
deerstands = ["Land_Misc_deerstand"]
wells = ["Land_Misc_Well_L_EP1", "Land_Misc_Well_C_EP1", "Land_Barrel_water", "land_smd_water_pump", "Land_pumpa", "misc_well", "misc_wellpump", "kasna_new"]
boat = ["Land_Nav_Boathouse", "Land_BoatSmall_2b", "land_molo"]
castle = ["Land_A_Castle_Bergfrit", "Land_A_Castle_Stairs_A", "Land_A_Castle_Gate", "Land_A_Castle_Wall2_End_2", "Land_A_Castle_WallS_End", "Land_A_Castle_Wall2_30", "Land_A_Castle_WallS_10", "Land_A_Castle_Donjon"]
church = ["Land_Church_01", "Land_Church_03", "Land_Church_02", "Land_Church_02a", "Land_Church_05R", "land_kostelik_final_2122", "Land_A_Mosque_small_2_EP1", "Land_A_Minaret_EP1"]
construction = ["Land_wagon_box", "Land_transport_cart_EP1", "Land_wagon_flat", "Land_wagon_tanker", "MAP_Misc_Greenhouse", "Misc_Cargo1Bo_military", "land_jzd_bezstrechy", "land_f_b1", "land_x_skladiste_low_tex"]
farm = ["Land_stodola_old_open", "Land_Farm_Cowshed_a", "Land_stodola_open", "Land_Barn_W_02", "Land_Farm_Cowshed_c", "Land_Farm_Cowshed_b", "Land_Shed_W02", "Land_sara_stodola", "land_domek_podhradi_1", "land_jzd_stodola2", "land_jzd_kr2", "land_jzd_kr1", "land_hut02", "land_hut01", "land_hut04", "Land_House_L_8_EP1", "Land_House_L_3_EP1", "Land_House_L_4_EP1", "Land_House_L_6_EP1", "land_smd_hut02", "land_smd_hut01", "land_smd_hut04", "Land_bouda2_vnitrek", "Land_smd_sara_stodola2", "land_jzd_stodola1", "land_plynom", "land_zd_2", "land_zd_1", "land_marsh1", "Land_Barn_W_01"]
hospital = ["Land_A_Hospital", "RU_WarfareBFieldhHospital", "USMC_WarfareBFieldhHospital", "MASH_EP1"]
industrial = ["Land_Ind_Workshop01_01", "Land_Ind_Garage01", "Land_Ind_Workshop01_02", "Land_Ind_Workshop01_04", "Land_Ind_Workshop01_L", "Land_Hangar_2", "Land_A_FuelStation_Build", "Land_Shed_W01", "Land_Tovarna2", "Land_Ind_Vysypka", "Land_A_BuildingWIP", "Land_Misc_Cargo1Ao", "Land_Misc_Cargo1Bo", "Land_telek1", "Land_Rail_House_01", "Land_Barn_Metal", "Land_Ind_Expedice_1", "Land_A_CraneCon", "Land_Ind_Mlyn_03", "Rubbish5", "Land_komin", "Land_Ind_Pec_01", "Land_Ind_SiloVelke_01", "Land_Misc_Garb_Heap_EP1", "Land_Shed_M02", "Fort_Barricade", "Land_Misc_Rubble_EP1", "Land_A_Crane_02b", "datsun01Wreck", "UralWreck", "Land_Misc_GContainer_Big", "Land_trafostanica_velka", "Misc_TyreHeap", "Land_sara_hasic_zbroj", "Land_Ind_Quarry", "Land_MBG_Warehouse", "Land_aif_tovarna1", "Land_MBG_Radiotelescope", "Land_House_C_10_EP1", "Land_MBG_Garage_Single_B", "Land_seb_bouda_plech", "Land_hut_old01", "land_bunka", "land_molovabud2", "land_molovabud1", "land_seb_rozvodna", "land_provoz2", "land_sklad2", "land_hala1", "land_seb_main_fac", "land_garaze", "Land_vys_budova_p1", "Land_Ind_Oil_Tower_EP1", "Land_tovarna1", "Land_Fort_Watchtower", "Land_ibr_FuelStation_Build", "Land_House_C_12_EP1", "Land_garaz_bez_tanku", "Land_leseni2x", "Land_smd_garaz_open", "Land_Ind_Oil_Pump_EP1", "land_provoz1", "land_b_small1", "land_seb_nasypka", "land_kontejner_des", "land_f_b2", "land_bud2", "land_seb_mine_main_opt", "land_seb_mine_near", "Land_Shed_Ind02", "Land_Misc_PowerStation", "Land_repair_center"]
military = ["Land_SS_hangar", "Camp", "CampEast", "CampEast_EP1", "Land_tent_east", "Land_Dam_ConcP_20", "C130J_wreck_EP1", "Barrack2", "Mi8Wreck", "USMC_WarfareBVehicleServicePoint", "Land_Vysilac_FM", "Land_Mil_Barracks_L", "Land_MBG_Killhouse_3", "Land_MBG_Killhouse_4", "Land_aif_strazni_vez", "Land_MBG_Killhouse_2", "Land_A_Villa_EP1", "land_pozorovatelna", "land_hlaska", "Land_MBG_Killhouse_1", "land_army_hut2_int", "land_army_hut_int", "Land_army_hut3_long_int", "Land_ibr_terminal", "Land_smd_garaz_s_tankem", "land_smd_army_hut2_int", "land_smd_army_hut2", "Land_smd_SS_hangar_withdoor", "Land_smd_army_hut3_long_int", "Land_smd_hlaska", "Land_Mil_hangar_EP1", "land_st_vez", "Land_mi8_crashed", "land_AII_middle_floor", "Land_AII_upper_part", "Land_Mil_Guardhouse_EP1", "Land_Mil_ControlTower", "Land_Mil_House", "Land_a_stationhouse", "Land_Mil_Barracks", "Land_A_TVTower_Base"]
military_special = ["Land_Mil_Barracks_i", "Land_budova4_in", "Land_kostel_trosky", "Land_budova4_winter", "Land_smd_budova4_in", "Land_smd_kostel_trosky", "land_AII_last_floor"]
misc = ["Land_Ind_Shed_02_main"]
office = ["Land_Panelak", "Land_Panelak2", "Land_rail_station_big", "Land_A_Office01", "land_vysoky1", "land_dlouhy2", "land_hotel_p2", "land_hotel_p1", "Land_A_Office02", "Land_aif_hotel", "Land_aif_hotel_bio", "land_mbg_apartments_big_04", "land_vysoky2", "land_dlouhy1", "Land_ibrPanelak", "Land_ibrPanelak2", "LAND_konecna", "Land_smd_dum_olez_istan1_open2", "Land_smd_hotel_riviera2", "Land_smd_hotel_riviera1", "Land_smd_hotel", "Land_smd_dum_istan4_detaily1", "Land_smd_dum_istan4", "Land_smd_hospoda_mesto", "Land_HouseB_Tenement"]
powerlines = ["Land_sloup_vn"]
residential = ["Land_kulna", "Land_hut06", "Land_Hlidac_budka", "Land_HouseV2_02_Interier", "Land_A_Pub_01", "Land_Shed_wooden", "Land_HouseBlock_A1_1", "Land_HouseV2_04_interier", "Land_HouseV2_01A", "Land_psi_bouda", "Land_KBud", "Land_HouseV_3I4", "Land_HouseV_3I1", "Land_HouseV_1T", "Land_HouseV_1L1", "Land_HouseV_1I2", "Land_HouseV_2L", "Land_houseV_2T2", "Land_HouseBlock_A1", "Land_HouseBlock_A2_1", "Land_HouseBlock_A3", "Land_HouseBlock_B5", "Land_HouseBlock_B6", "Land_HouseBlock_C1", "Land_HouseV2_01B", "Land_HouseV2_03", "LADAWreck", "SKODAWreck", "Land_GuardShed", "RU_WarfareBBarracks", "Land_NAV_Lighthouse", "Land_Panelak3", "Land_sara_Domek_sedy", "land_mbg_brickhouse_01", "Land_dum_mesto_in", "Land_dum_mesto2", "Land_MBG_GER_ESTATE_2", "Land_MBG_GER_HUS_4", "Land_dum_rasovna", "Land_cihlovej_dum_in", "Land_MBG_GER_RHUS_1", "Land_MBG_GER_RHUS_2", "Land_MBG_GER_PUB_2", "Land_sara_domek_vilka", "Land_mbg_apartments_big_01", "Land_dum_ras", "Land_deutshe_mini", "land_seb_bouda1", "land_x_vez_tex", "Land_House_K_3_EP1", "Land_House_C_5_V2_EP1", "Land_House_C_5_V3_EP1", "Land_House_L_1_EP1", "Land_House_C_5_V1_EP1", "Land_House_C_2_EP1", "Land_House_K_7_EP1", "Land_House_C_4_EP1", "Land_House_C_11_EP1", "Land_House_C_1_EP1", "Land_dum_istan3_hromada2", "Land_House_C_3_EP1", "Land_House_C_1_v2_EP1", "Land_House_C_9_EP1", "Land_House_K_1_EP1", "Land_House_K_8_EP1", "Land_House_C_5_EP1", "Land_dum_istan3_pumpa", "land_sara_domek_kovarna", "land_sara_domek_hospoda", "LAND_vokzal_big", "LAND_Zachytka", "LAND_hospoda ", "LAND_Kiosk2", "LAND_skola", "LAND_Tav_Panelak2", "LAND_Tav_panelak", "LAND_Tav_Panelak3", "LAND_Big_Panelak", "LAND_Posta", "Land_smd_dum_istan2b", "Land_smd_dum_olez_istan1_open", "Land_smd_dum_olez_istan2_maly_open", "Land_smd_dum_olez_istan2_open", "Land_smd_house_y_open", "Land_majak", "Land_smd_sara_zluty_statek_in", "Land_smd_dum_olezlina_open", "Land_majak2", "Land_smd_budova3_open", "Land_budova5", "Land_smd_dum_istan3_hromada", "Land_smd_kasarna", "Land_House_L_7_EP1", "Land_House_K_6_EP1", "land_seb_bouda3", "land_seb_mine_maringotka", "Land_Shed_W4", "Land_HouseV_1I1", "Land_HouseV_1L2", "Land_HouseV_3I3", "Land_HouseV_1I3", "Land_HouseV_1I4", "Land_Mil_Guardhouse", "Land_A_MunicipalOffice", "Land_sara_domek_zluty"]
residential_ruins = ["Land_ruin_corner_1", "Land_ruin_walldoor", "MAP_R_HouseV2_02", "MAP_R_HouseV2_03B", "MAP_R_HouseV2_04", "MAP_R_HouseV_2L", "MAP_ruiny_kopa_big", "MAP_sara_domek_vilka_ruins", "Land_ruin_01", "Land_afbarabizna", "Land_dum_zboreny", "land_seb_residental", "Land_House_L_9_EP1", "Land_dum_zboreny_total", "Land_dulni_bs"]
supermarket = ["Land_A_GeneralStore_01a", "Land_A_GeneralStore_01", "LAND_shopping_sab5", "LAND_shopping_sab1"]


search = supermarket


with open('C:\\Users\\Fabio\\WebstormProjects\\DayZMap\\tools\\assets\\objects\\poiObjects.txt', 'r') as f:
    coords = []
    for line in f:
        found = False
        for obj in search:
            if obj.lower().replace('land_', '') in line.lower():
                found = True
                break
        if not found:
            continue
        data = line.split(';')
        coords.append([float(data[1]), float(data[2])])

    out = '[\n'
    for coord in coords:
        out += f'  [{coord[0]}, {coord[1]}],\n'
    out += ']'
    print(out)
